development:
  adapter: async

test:
  adapter: test

productione:
  adapter: redis
  url: redis://default:Bt3O0l8Bw1ukSmCAqwGfFgF3mrkumP8J@redis-18019.c226.eu-west-1-3.ec2.cloud.redislabs.com:18019
  channel_prefix: buddy_production
